# Generated by Django 5.2.7 on 2025-10-12 21:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Evento')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Participante')),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingresa un correo electrónico válido.')], verbose_name='Correo Electrónico')),
                ('evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='my_app.evento', verbose_name='Evento Asociado')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('evento', 'correo')},
            },
        ),
    ]
